spring:
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/meij_dev?useUnicode=true&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver


#debug: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: tk.mybatis.springboot.model
